# itk-version: 3.1.1

networks:
  app:
    driver: bridge
    internal: false

services:
  elasticsearch:
    image: elasticsearch:8.13.0
    restart: unless-stopped
    networks:
      - app
      - ${IMPORTS_NETWORK_NAME:-eventbackend_app}
      - ${API_NETWORK_NAME:-eventapi_app}
    deploy:
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 4096M
    user: "1042"
    volumes:
      - ./.docker/data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

#  Should only be used if we need to have write access in the API (frontend).
#  rabbit:
#    image: rabbitmq:3.12.4-alpine
#    networks:
#      - app
#      - ${IMPORTS_NETWORK_NAME:-eventbackend_app}
#      - ${API_NETWORK_NAME:-eventapi_app}
#    environment:
#      - RABBITMQ_DEFAULT_USER=user
#      - RABBITMQ_DEFAULT_PASS=password
#      - RABBITMQ_ERLANG_COOKIE='d53f319cd7376f8f840aaf9889f315ab
